#include<iostream>
#include<string>

using namespace std;

/*
	宝石与石头
	其实这个问题暴力解决最简单了，也不会有什么大的性能问题,除非平均一个字符串的数量达到了上百万个
	由于题目限制不超过50个，所以绝不会有性能问题
	并且下面的方案1只能是J字符串没有重复的情况下适用，如果出现重复就会出现错误
	方案2使用与一般任何情况
*/
class Solution {
public:
	/*
		方案1，暴力解决
		复杂度为O(m*n)
	*/
	//int numJewelsInStones(string J, string S) {
	//	int sum = 0;
	//	for (int i = 0; i < S.length(); ++i){
	//		for (int k = 0; k < J.length(); ++k){
	//			if (S[i] == J[k]){
	//				sum++;
	//			}
	//		}
	//	}
	//	return sum;
	//}

	/*
		方案2，优化，用空间替换时间
		复杂度为：O(m+n)
	*/
	int numJewelsInStones(string J, string S) {
		//'A' ASCII code is 65
		//'z' ASCII code is 122

		bool jewels[58]; //为什么是58 因为 122-65 + 1 = 58
		memset(jewels, false, sizeof(jewels)); //最快的方式将数组jewels全置为false
		for (int i = 0; i < J.length(); i++) {
			jewels[J[i] - 65] = true; //将J中出现的标识位设置为true
		}
		int result = 0;
		for (int i = 0; i < S.length(); i++) {
			if (jewels[S[i] - 65]) { //s[i] - 65得到0~57的数值，如果S出现过，那么就说明找到一个宝石了！
				result++;
			}
		}
		return result;
	}
};

void main(){
	Solution so;
	int num = so.numJewelsInStones("qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM", 
		"HUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNHUESAHHUANGJIJINGWENHUANGJINGWENHUANGJISdsaufenfeasdejnapfenfejisadjJIFHAUjiasjdenanfeapsjdehfnasjdnixdjeifhaujsidjiedaonsudjueaAdefjigehafjefbeufEFAFGDEFAMSKAJDIWEHFEIFNASJHNDUIEFHABNSJDNaAAbbbbjenfuASJPFAOPSFIEFNJEFNASHDUEFHNAJNDSJDADSJAIDSUDIEANJSNXJDHAOIHEUHFUAOSJDIOEWAIefhajfnsajfbchufheufanfkaajsdjaipeUJHFNAOHFA");
	cout << num << endl;
	system("pause");
}